services:
  resourcespace:
    build: .
    container_name: resourcespace
    restart: unless-stopped
    depends_on:
      - mariadb
    volumes:
      - filestore:/var/www/html/filestore
      - ./config.php:/var/www/html/include/config.php
    networks:
      - frontend
      - backend
    ports:
      - "80:80"
    env_file:
      - localhost.env
      - db.env

  companion:
    image: transloadit/companion:4.15.1
    container_name: companion
    restart: unless-stopped
    ports:
      - "8080:8080"
    network_mode: "host"
    env_file:
      - companion.env
      - companionSecrets.env

  mariadb:
    image: mariadb
    container_name: mariadb
    restart: unless-stopped
    env_file:
      - db.env
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - backend

networks:
  frontend:
  backend:

volumes:
  mariadb:
  filestore:
