name: Publish Docker container

on:
  push:
    branches:
      - main  # or the default branch of your repository

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Check out the repo
      uses: actions/checkout@v3

    - name: Get short SHA
      id: short-sha
      run: echo "::set-output name=sha::$(echo $GITHUB_SHA | cut -c1-6)"

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: set lower case repository name
      run: |
        echo "REPO=${GITHUB_REPOSITORY@L}" >> ${GITHUB_ENV}
      env:
        REPO: '${{ github.repository }}'

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        cache-from: type=gha
        cache-to: type=gha,mode=max`
        file: ./Dockerfile
        push: true
        tags: |
          ghcr.io/${{ env.REPO }}/resourcespace:latest
          ghcr.io/${{ env.REPO }}/resourcespace:${{ steps.short-sha.outputs.sha }}